app:
  welcome.endpoint: /welcome
  auth:
    endpoint: /login
    logout.endpoint: /logout
    form.endpoint: /login-page

spring.datasource:
  url: jdbc:postgresql://127.0.0.1:5432/bank
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
  testWhileIdle: true
  validationQuery: SELECT 1

spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
    ddl-auto: create-drop
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

logging.level:
  secureBanking.web: DEBUG
  org.springframework:
    core: WARN
    beans: WARN
    context: WARN
    web: WARN
    scheduling: WARN